name: "vi2en_model"
backend: "python"
max_batch_size: 1000


input [
  {
    name: "input_ids"
    data_type: TYPE_INT32
    dims: [ -1]
  }
]

output [
  {
    name: "output_ids"
    data_type: TYPE_INT32
    dims: [ -1]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]